# Generated by Django 3.1.3 on 2020-11-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
