# Generated by Django 3.1.3 on 2021-01-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210102_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='start_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
