# Generated by Django 3.1.3 on 2020-11-26 12:52

from django.db import migrations, models
import locations.validations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20201116_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default=None, max_length=100, validators=[locations.validations.name_validator]),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=None, max_length=100, validators=[locations.validations.name_validator]),
        ),
    ]
