# Generated by Django 3.1.3 on 2020-11-26 12:53

from django.db import migrations, models
import locations.validations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20201126_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, validators=[locations.validations.name_validator]),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100, validators=[locations.validations.name_validator]),
        ),
    ]
