# Generated by Django 3.1.3 on 2020-11-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20201126_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='longitude',
        ),
    ]
