# Generated by Django 3.1.3 on 2020-11-26 13:07

from django.db import migrations, models
import locations.validations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20201126_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, unique=True, validators=[locations.validations.mail_validator]),
        ),
    ]
