# Generated by Django 3.1.3 on 2021-01-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210104_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
