# Generated by Django 3.1.3 on 2020-11-27 12:00

from django.db import migrations, models
import locations.validations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20201126_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=None, max_length=100, validators=[locations.validations.pass_validator]),
        ),
    ]
