# Generated by Django 3.1.3 on 2020-11-27 12:00

from django.db import migrations, models
import locations.validations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=100, validators=[locations.validations.pass_validator]),
        ),
    ]
