# Generated by Django 3.1.3 on 2020-12-30 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import locations.validations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0008_auto_20201127_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitute', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[locations.validations.name_validator])),
                ('last_name', models.CharField(max_length=100, validators=[locations.validations.name_validator])),
                ('email', models.CharField(max_length=100, validators=[locations.validations.mail_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='locations',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.profile'),
        ),
    ]
